### ISSUE TITLE
Config: core_dir and root relation

### ISSUE THREAD

**Issue by vladra** [dry-rb/dry-component#18]
When `core_dir` and `root` folders are not related, `Dry::Component` fails to require file.

```
- config
  |- boot
    - config.rb
  boot.rb
- lib
```

```ruby
config.root = Pathname.new('lib')
config.core_dir = '../config'
```

Fails to require here:
https://github.com/dry-rb/dry-component/blob/master/lib/dry/component/container.rb#L119

Though file existence checked here:
https://github.com/dry-rb/dry-component/blob/master/lib/dry/component/container.rb#L211

```
LoadError: cannot load such file -- config/boot/config
/usr/local/lib/ruby/gems/2.3.0/gems/dry-component-0.3.0/lib/dry/component/container.rb:119:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/dry-component-0.3.0/lib/dry/component/container.rb:119:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/dry-component-0.3.0/lib/dry/component/container.rb:118:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/dry-component-0.3.0/lib/dry/component/container.rb:118:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/dry-component-0.3.0/lib/dry/component/container.rb:108:in `boot'
/usr/local/lib/ruby/gems/2.3.0/gems/dry-component-0.3.0/lib/dry/component/container.rb:96:in `boot!'
```

So, this is a bug, or I should never use `core_dir` location out of `root` location?

**Comment by vladra** [comment]
Not relevant anymore, I've just changed my folder structure. Having an ability to pass more options to auto register could be nice though.
